#Site settings
title: stereotopia
description: Stereotopia is a website with it's finger on the pulse of a world enamoured with digital media.
baseurl: ""

#Build Settings
permalink: /:title/

plugins: 
         - jekyll-sitemap